### ISSUE TITLE
ArrayCard组件预览时报错

### ISSUE THREAD

**Issue by jingjingzhao** [seada-low-code/lowcode-ecology#12]
ArrayCard组件预览时报错，报错如下：
![image](https://user-images.githubusercontent.com/5880014/181720801-4ca650b3-fa2f-4f59-acb8-889f316170fe.png)

使用的是 `@seada/formily-materials@0.0.1-rc.6` 版本

**Comment by Immanding** [comment]
是向arraycard中拖入任意组件都会报错吗？

**Comment by jingjingzhao** [comment]
> 是向arraycard中拖入任意组件都会报错吗？

知道报错的原因了。是因为没有往 ArrayCards 里拖拽任何组件导致的。加上子组件后，预览就正常了。关闭吧

**Comment by Immanding** [comment]
> 



> > 是向arraycard中拖入任意组件都会报错吗？
> 
> 知道报错的原因了。是因为没有往 ArrayCards 里拖拽任何组件导致的。加上子组件后，预览就正常了

不拖入组件也不应该报错，这里我后面看看
