### ISSUE TITLE
antd-pro 场景 选择出码后build项目报错 找不到@seada/antd-materials/src/index.tsx 地址 

### ISSUE THREAD

**Issue by zhoulisuper** [seada-low-code/lowcode-ecology#14]
antd-pro 场景 选择出码后build项目报错 找不到@seada/antd-materials/src/index.tsx 地址

**Comment by haloworld007** [comment]
这是在官方demo里面出码导致的报错吗？

**Comment by zhoulisuper** [comment]
是的 官方demo



在 2022-09-01 18:39:18，"haloworld" ***@***.***> 写道：

这是在官方demo里面出码导致的报错吗？

**Comment by twinkle77** [comment]
发包的时候，只执行了 ```npm run lowcode:build```
但没有执行 ```npm run build``` 会有这个问题

**Comment by haloworld007** [comment]
> 发包的时候，只执行了 `npm run lowcode:build` 但没有执行 `npm run build` 会有这个问题

是包的路径定义问题，修改为 `@seada/antd-materials` 即可
