### ISSUE TITLE
官方线上 demo 的场景 antd + formily 场景有问题，导致拉取到项目中出现相同问题

### ISSUE THREAD

**Issue by kevinbolton729** [seada-low-code/lowcode-ecology#19]
可以看下详细的 Bug 描述（lowcode-engine/issue/1008 [#1008](https://github.com/alibaba/lowcode-engine/issues/1008) ）中已提 issue

**Comment by Immanding** [comment]
@twinkle77

**Comment by twinkle77** [comment]
done 了，已给 lowcode-demo 提 pr
