### ISSUE TITLE
预览报错，导致无法预览

### ISSUE THREAD

**Issue by jingjingzhao** [seada-low-code/lowcode-ecology#22]
页面上只配置了个「标题」组件，点击「预览」报错了
![image](https://user-images.githubusercontent.com/5880014/188541675-3d507143-378f-43f5-8658-517b4c593f04.png)

![image](https://user-images.githubusercontent.com/5880014/188541362-0a640eb0-aa55-4001-a1c0-05e84a17f44c.png)
lowcode-ecology版本是：`v1.0.0-rc.12`

**Comment by jingjingzhao** [comment]
我本地代码导致的，问题关闭

**Comment by twinkle77** [comment]
https://github.com/seada-low-code/lowcode-ecology/pull/20/commits/3f2f2294cf8642807b66fc00a861eff667f55860
