### ISSUE TITLE
求助，formily里提交按钮onclick的逻辑处理

### ISSUE THREAD

**Issue by jingjingzhao** [seada-low-code/lowcode-ecology#23]
formily里提交按钮onclick的逻辑处理，是需要用户自己配置上去吗？onclick事件的实现都由用户自己完成吗？

**Comment by Immanding** [comment]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/19871501/188546754-0d177cf4-8fca-448a-a310-844ea6ac2243.png">
是的，没有封装submit button，可以自己拖一个button进去，在js面板绑定click事件事件进行处理，formily实例可以通过ref属性获得
