### ISSUE TITLE
ProTable 没有暴露pageTotal属性

### ISSUE THREAD

**Issue by dandananddada** [seada-low-code/lowcode-ecology#25]
包括 查询表格 CURD 表格在内的 ProTable 都没有暴漏出分页总数设置项。
<img width="1001" alt="CleanShot 2022-11-03 at 12 02 46@2x" src="https://user-images.githubusercontent.com/7675681/199645440-5d254601-b471-46e1-a635-0a3b4d6f0c44.png">

**Comment by Immanding** [comment]
分页总数我理解是由接口返回的total属性确定的，具体可以参考 antd protable api
@twinkle77 cc

**Comment by twinkle77** [comment]
> 分页总数我理解是由接口返回的total属性确定的，具体可以参考 antd protable api @twinkle77 cc

是的，绑定一个 request 函数就可以的，pro-table 只要 total 总数就可以了

```
// 示例请求
  async queryList(params) {
    // 参数处理 currentpageSize 为分页参数、other 为其他过滤条件
    const { current, pageSize, ...other } = params

    console.log('查询参数: ', params)

    // 想传参的话，把 params 传给 load
    const response = await this.dataSourceMap.query.load({
      current,
      pageSize,
      ...other
    })

    console.log('查询结果', response)

    if (response.code !== 0) {
      return {
        data: [],
        total: 0
      }
    }

    return {
      data: response?.result?.data,
      total: response?.result?.total
    }
  }
```

@dandananddada
