### ISSUE TITLE
本地跑这个lerna工程的时候报错An unexpected error occurred: "https://npm.shopee.io/@seada%2flowcode-code-generator/-/lowcode-code-generator-1.0.1-beta.1.tgz: getaddrinfo ENOTFOUND npm.shopee.io".

### ISSUE THREAD

**Issue by ming001** [seada-low-code/lowcode-ecology#31]
把仓库拉到本地之后，执行yarn bootstrap，这时候报An unexpected error occurred: "https://npm.shopee.io/@seada%2flowcode-code-generator/-/lowcode-code-generator-1.0.1-beta.1.tgz: getaddrinfo ENOTFOUND npm.shopee.io".错误
![image](https://user-images.githubusercontent.com/24415457/204468355-9bd64f9d-a13c-4f03-8d7d-3ed2c1a5e062.png)

**Comment by haloworld007** [comment]
fixed

**Comment by ming001** [comment]
> fixed

我需要什么操作吗，我重新执行了yarn bootstrap,还是报那个错误
error An unexpected error occurred: "https://npm.shopee.io/@seada%2flowcode-code-generator/-/lowcode-code-generator-1.0.1-beta.1.tgz: getaddrinfo ENOTFOUND npm.shopee.io".

**Comment by laosandegudai** [comment]
问题依然存在，https://npm.shopee.io/@seada%2flowcode-code-generator/-/lowcode-code-generator-1.0.1-beta.1.tgz 是无法访问的

**Comment by Immanding** [comment]
> 问题依然存在，https://npm.shopee.io/@seada%2flowcode-code-generator/-/lowcode-code-generator-1.0.1-beta.1.tgz 是无法访问的

.yarnrc 没有生效，你可以先删除 demo/yarn.lock文件以及node_modules依赖，重新安装一下就好
