### ISSUE TITLE
默认值无效

### ISSUE THREAD

**Issue by shuxiaoman** [seada-low-code/lowcode-ecology#37]
低代码项目，lowcode-engine升级到1.0.15版本后，多次拖入同一个组件（例如：ArrayCards），组件schema不会生成默认值。[官方解决办法](https://github.com/alibaba/lowcode-engine/issues/1045)，具体原因不知道
![image](https://user-images.githubusercontent.com/40754866/208667072-e6943305-470b-481d-85fe-f8bc63a7dbba.png)

**Comment by Immanding** [comment]
理解你的意思了，可以提个mr我合一下

**Comment by shuxiaoman** [comment]
> 理解你的意思了，可以提个mr我合一下

https://github.com/seada-low-code/lowcode-ecology/pull/38

**Comment by shuxiaoman** [comment]
> 理解你的意思了，可以提个mr我合一下

刚刚试了下，升级到lowcode-engine@1.0.17后，设置initialValue也没效果了。

复现步骤：
1. 打开 [demo](https://lowcode-engine.cn/demo/demo-antd-pro-with-formily/index.html)；
2. 拖拽一个FormilyForm组件；
3. 再往里面拖拽一个ArrayCards组件；
4. ArrayCards组件没有添加按钮；

**Comment by Immanding** [comment]
fixed at v1.0.0-rc24
