### ISSUE TITLE
初始化参数失效

### ISSUE THREAD

**Issue by shuxiaoman** [seada-low-code/lowcode-ecology#41]
# 升级最新版本后默认值无效

## 版本信息

- "@alilc/lowcode-engine": "^1.0.17"
- "@alilc/lowcode-engine-ext": "^1.0.5"
- "@seada/antd-plugins": "1.0.0-rc.24"

## 复现步骤

1. 进入文件：packages/formily-materials/lowcode/formily-array-cards/propsSchema.ts
2. 添加参数：![image](https://user-images.githubusercontent.com/40754866/209325806-adcc3868-d9b2-4790-a84a-e5b94d08bf36.png)
3. 拖拽FormilyArrayCards组件
4. schema没有默认值

## 猜测原因
![image](https://user-images.githubusercontent.com/40754866/209328035-a547f12a-af9a-4311-9b4d-8f922ad1228a.png)

**Comment by Immanding** [comment]
试试升级formily-material 至1.0.0-rc.24
#37

**Comment by Immanding** [comment]
不合规的地方可以提个PR改一下，meta修改后预期是需要重新刷新页面加载meta.js才能生效

**Comment by shuxiaoman** [comment]
> 不合规的地方可以提个PR改一下，meta修改后预期是需要重新刷新页面加载meta.js才能生效

[提了哦](https://github.com/seada-low-code/lowcode-ecology/pull/42)

**Comment by Immanding** [comment]
> > 不合规的地方可以提个PR改一下，meta修改后预期是需要重新刷新页面加载meta.js才能生效
> 
> [提了哦](https://github.com/seada-low-code/lowcode-ecology/pull/42)

OK，稍后我验证一下再部署新版本
