### ISSUE TITLE
启动项目后控制台报错

### ISSUE THREAD

**Issue by Andrew-Zn** [seada-low-code/lowcode-ecology#43]
下载的最新版本 
node 版本：v14.20.0
按照 文档 yarn bootstrap  ， yarn start 
访问localhost:8000 ，页面空白控制台报错

错误信息如下： 
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/31008185/210517134-7cb492bf-825e-490e-83d0-7baf3ef62c10.png">

**Comment by Immanding** [comment]
重新删掉依赖安装试试

**Comment by WuShenghui** [comment]
升级`lowcode-engine` 和 `lowcode-engine-ext` 为最新版本可解决：

将 `demo/.umirc.ts` 文件中

```
scripts: [
    ...
    'https://alifd.alicdn.com/npm/@alilc/lowcode-engine@1.0.17/dist/js/engine-core.js',
    'https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@1.0.5/dist/js/engine-ext.js'
]
```

修改为

```
scripts: [
    ...
    'https://alifd.alicdn.com/npm/@alilc/lowcode-engine@latest/dist/js/engine-core.js',
    'https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@latest/dist/js/engine-ext.js',
]
```
