### ISSUE TITLE
求助：Windows安装报错

### ISSUE THREAD

**Issue by owenchen1004** [seada-low-code/lowcode-ecology#47]
node16和12都试过了，yarn bootstrap之后都会报错，求助~~必须要用mac嘛

在packages/antd-material里面run lowcode:dev也报错，Windows是跑不起来吗？生成的.tmp里面引用路径是错的

**Comment by owenchen1004** [comment]
在packages/antd-material里面run lowcode:dev也报错，Windows是跑不起来吗

**Comment by haloworld007** [comment]
报错信息贴出来看看

**Comment by owenchen1004** [comment]
我像改一下material里面的设置器，在antd-material里面yarn lowcode：dev之后报这个错误：

yarn run v1.22.19
$ build-scripts start --config ./build.lowcode.js --port 5551
@alib/build-scripts 0.1.32
0: /usr/bin/node
1: /home/lowcode/lowcode-ecology/node_modules/@alib/build-scripts/bin/child-process-start.js
2: start
3: --config
4: ./build.lowcode.js
5: --port
6: 5551
                                         10% buildingℹ ｢wds｣: Project is running at http://0.0.0.0:5551/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /home/lowcode/lowcode-ecology/packages/antd-materials
                                         100%
info WEBPACK Hash: 53aa903805964cdd0356
info WEBPACK Version: webpack 4.46.0
info WEBPACK Child
info WEBPACK     Hash: 53aa903805964cdd0356
info WEBPACK     Time: 16724ms
info WEBPACK     Built at: 03/08/2023 11:20:25 AM
info WEBPACK              Asset      Size   Chunks                   Chunk Names
info WEBPACK      designer.html  10.1 KiB           [emitted]
info WEBPACK         index.html  10.1 KiB           [emitted]
info WEBPACK           index.js   483 KiB    index  [emitted]        index
info WEBPACK       index.js.map   493 KiB    index  [emitted] [dev]  index
info WEBPACK            meta.js   472 KiB     meta  [emitted]        meta
info WEBPACK        meta.js.map   541 KiB     meta  [emitted] [dev]  meta
info WEBPACK       preview.html  1.47 KiB           [emitted]
info WEBPACK         preview.js  2.59 MiB  preview  [emitted]        preview
info WEBPACK     preview.js.map  2.66 MiB  preview  [emitted] [dev]  preview
info WEBPACK            view.js  8.95 MiB     view  [emitted]        view
info WEBPACK        view.js.map  8.02 MiB     view  [emitted] [dev]  view
info WEBPACK     Child html-webpack-plugin for "designer.html":
info WEBPACK                 Asset     Size  Chunks  Chunk Names
info WEBPACK         designer.html  548 KiB       0
info WEBPACK     Child html-webpack-plugin for "index.html":
info WEBPACK              Asset     Size  Chunks  Chunk Names
info WEBPACK         index.html  548 KiB       0
info WEBPACK     Child html-webpack-plugin for "preview.html":
info WEBPACK                Asset     Size  Chunks  Chunk Names
info WEBPACK         preview.html  540 KiB       0
ERR! (undefined) ./src/index.scss (/home/lowcode/lowcode-ecology/node_modules/css-loader/dist/cjs.js??ref--6-2!/home/lowcode/lowcode-ecology/node_modules/postcss-loader/src??ref--6-3!/home/lowcode/lowcode-ecology/node_modules/sass-loader/dist/cjs.js??ref--6-4!./src/index.scss)
ERR! Error: Missing binding /home/lowcode/lowcode-ecology/node_modules/node-sass/vendor/linux-x64-83/binding.node
ERR! Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 14.x
ERR!
ERR! Found bindings for the following environments:
ERR!   - Linux 64-bit with Node.js 14.x
ERR!
ERR! This usually happens because your environment has changed since running `npm install`.
ERR! Run `npm rebuild node-sass` to download the binding for your current environment.

**Comment by owenchen1004** [comment]
npm rebuild node-sass 运行了也无效，弄得版本是14.21.3

**Comment by haloworld007** [comment]
因为我们目前都是使用 mac 开发，无法在 windows 下验证你的错误，你可以尝试这么做：

1. 清除依赖和缓存，再重新安装依赖

```
rm -rf node_modules
npm cache clean --force
npm i
npm rebuild node-sass --force
```

如果仍然无法解决，尝试第二步。

2. 使用阿里脚手架初始化一个物料项目，看看脚手架是否能够跑起来。如果也跑不起来，证明脚手架对 windows 的支持本身有就问题，可能得推动 [阿里低代码引擎](https://github.com/alibaba/lowcode-engine) 官方去修复。

初始化脚手架请参考[新组件开发](https://lowcode-engine.cn/site/docs/guide/expand/editor/material#%E6%96%B0%E5%BC%80%E5%8F%91%E7%BB%84%E4%BB%B6)
