### ISSUE TITLE
formily.-materials的物料仓库array-table功能使用失效，却当作物料引入时又是正常的

### ISSUE THREAD

**Issue by rongrongt** [seada-low-code/lowcode-ecology#48]
![WechatIMG76](https://user-images.githubusercontent.com/21823510/224032218-bc597cfa-9904-4a9b-b929-6cdcef2eea33.jpeg)
![WechatIMG73](https://user-images.githubusercontent.com/21823510/224032259-ff72bdd8-4fab-426f-96bc-0e860714fd32.jpeg)
下载本仓库的formily.-materials的物料仓库并且用lowcode:dev运行在端口5551上，发现使用array-table去添加一列时报错，
但是在端口为5556的低代码平台中去引用了该物料仓库，在图片右边界面上5556的低代码平台上可以正常的操作array-table, 比如添加1列。但是在左边5551物料仓库中就同样去操作添加列就报错了，

报错内容是无法找到name, 就是控制台里显示的那行。我奇怪，同一个物料仓库，为啥在物料仓库里跑起来的界面上无法操作，被引入的地方却可以使用

本地已使用x-switch做了正确代理

**Comment by rongrongt** [comment]
我刚刚试了下，仅在官方demo仓库demo-antd-pro-with-formily中可以正常使用，在其他仓库中也无法使用

**Comment by Immanding** [comment]
可以检查一下是否是插件没有初始化呢？

**Comment by Immanding** [comment]
fixed
