### ISSUE TITLE
form嵌套能力的实现

### ISSUE THREAD

**Issue by BingBlog** [seada-low-code/lowcode-ecology#5]
## 问题
- 如下所示，使用formily的Schema Markup方式或者完全schema的方式，都可以实现表单的嵌套； 
``` jsx
/**
 * @desc 构建全局和局部，并实现全局和局部查询参数的联动
 * 1、日周月的类型会影响分析日期和对比日期
 * 2、实时情况下，展示分时和累计切换
 * 3、对比日期场景下，展示对比时间选择
 *
 */
import React from 'react';
import {
  Input,
  Select,
  FormItem,
  FormButtonGroup,
  Submit,
  FormLayout,
  TreeSelect,
  DatePicker,
  Radio,
  Checkbox,
  Space,
} from '@formily/antd';
import {
  createForm,
  onFormInit,
  onFormMount,
  onFormUnmount,
  onFormReact,
  onFormValuesChange,
  onFormSubmit,
  onFormSubmitStart,
  onFormSubmitEnd,
  onFormInitialValuesChange,
  onFormInputChange,
} from '@formily/core';
import { FormProvider, Field, createSchemaField } from '@formily/react';
import { FormilyTable } from './components/table';

import 'antd/dist/antd.css';
import './index.less';

const form = createForm({
  effects() {
    onFormInit(() => {
      console.log('表单已初始化: ', form);
    });
    onFormMount(() => {
      form.setValues({}, 'deepMerge');
      console.log('表单已挂载: ', form.values);
    });
    onFormValuesChange((form) => {
      console.log('表单值变化: ', form.values);
    });
  },
});

const SchemaField = createSchemaField({
  components: {
    FormItem,
    Input,
    DatePicker,
    Radio,
    Checkbox,
    Space,
    FormLayout,
    FormilyTable,
  },
});

export default () => {
  return (
    <>
      <FormProvider form={form}>
        <SchemaField>
          {/*************** topGlobal start ***************/}
          <SchemaField.Void
            x-component="FormLayout"
            x-component-props={{
              layout: 'inline',
              labelAlign: 'right',
              wrapperAlign: 'left',
              className: 'material-search-form',
            }}
          >
            <SchemaField.Object name="topGlobal">
              <SchemaField.String
                name="dateType"
                x-component="Radio.Group"
                x-component-props={{
                  options: [
                    { label: '日', value: 'day' },
                    { label: '周', value: 'week' },
                    { label: '月', value: 'month' },
                  ],
                  optionType: 'button',
                }}
                x-decorator="FormItem"
                default={2}
              />
              <SchemaField.String
                name="timeType"
                x-component="Radio.Group"
                x-component-props={{
                  options: [
                    { label: '离线', value: 2 },
                    { label: '实时', value: 1 },
                  ],
                  optionType: 'button',
                }}
                x-decorator="FormItem"
                default={2}
              />
              <SchemaField.String
                name="analysticTimeType"
                default={1}
                x-component-props={{
                  options: [
                    { label: '分时', value: 1 },
                    { label: '累计', value: 2 },
                  ],
                  optionType: 'button',
                }}
                x-component="Radio.Group"
                x-decorator="FormItem"
                x-reactions={{
                  fulfill: {
                    state: {
                      display: '{{$values.topGlobal.timeType === 1 ? "visible" : "none"}}',
                    },
                  },
                }}
              />
            </SchemaField.Object>
          </SchemaField.Void>
          {/*************** coreIndex start ***************/}
          {/*************** coreIndex filter start ***************/}
          <SchemaField.Void
            x-component="FormLayout"
            x-component-props={{
              layout: 'inline',
              labelAlign: 'right',
              wrapperAlign: 'left',
              className: 'material-search-form',
            }}
          >
            <SchemaField.Object name="coreIndex">
              <SchemaField.String
                name="date"
                x-component="DatePicker"
                x-decorator="FormItem"
                x-reactions={{
                  fulfill: {
                    schema: {
                      'x-component-props.picker': '{{$values.topGlobal.dateType}}',
                    },
                  },
                }}
              />
              <SchemaField.String
                name="ratio"
                default={['_hb_ratio']}
                enum={[
                  { label: '日环比', value: '_hb_ratio' },
                  { label: '周同比', value: '_tb_ratio' },
                  { label: '对比', value: '_compare_ratio' },
                ]}
                x-component="Checkbox.Group"
                x-decorator="FormItem"
              />
              <SchemaField.String
                name="compareDate"
                title="对比时间"
                x-component="DatePicker"
                x-decorator="FormItem"
                x-reactions={{
                  fulfill: {
                    state: {
                      display:
                        '{{$values.coreIndex.ratio.includes("_compare_ratio") ? "visible" : "none"}}',
                    },
                    schema: {
                      'x-component-props.picker': '{{$values.topGlobal.dateType}}',
                    },
                  },
                }}
              />
            </SchemaField.Object>
          </SchemaField.Void>
          {/*************** coreIndex table start ***************/}
          <SchemaField.Void
            x-component="FormLayout"
            x-component-props={{
              layout: 'vertical',
              wrapperWidth: '100%',
            }}
          >
            <SchemaField.Object name="coreIndexTable">
              <SchemaField.String
                name="selectedNames"
                default={{
                  selectedRowKeys: []
                }}
                x-component="FormilyTable"
                x-decorator="FormItem"
                x-component-props={{
                  columns: [
                    {
                      title: '姓名',
                      dataIndex: 'name',
                      key: 'name',
                    },
                    {
                      title: '年龄',
                      dataIndex: 'age',
                      key: 'age',
                    },
                    {
                      title: '住址',
                      dataIndex: 'address',
                      key: 'address',
                    },
                  ]
                }}
                x-reactions={{
                  fulfill: {
                    schema: {
                      'x-component-props.filterParams': '{{Object.assign({}, $values.topGlobal, $values.coreIndex)}}',
                    },
                  },
                }}
              />
            </SchemaField.Object>
          </SchemaField.Void>
          {/*************** coreIndex chart start ***************/}
          <SchemaField.Void
            x-component="FormLayout"
            x-component-props={{
              layout: 'vertical',
              wrapperWidth: '100%',
            }}
          >
            <SchemaField.Object name="coreIndexTable2">
              <SchemaField.String
                name="selectedChart"
                x-component="FormilyTable"
                x-decorator="FormItem"
                x-component-props={{
                  columns: [
                    {
                      title: '姓名',
                      dataIndex: 'name',
                      key: 'name',
                    },
                    {
                      title: '年龄',
                      dataIndex: 'age',
                      key: 'age',
                    },
                    {
                      title: '住址',
                      dataIndex: 'address',
                      key: 'address',
                    },
                  ]
                }}
                x-reactions={{
                  fulfill: {
                    state: {
                      display:
                        '{{ $values.coreIndexTable.selectedNames.selectedRowKeys.length > 0 ? "visible" : "none" }}',
                    },
                    schema: {
                      'x-component-props.filterParams': '{{Object.assign({}, $values.topGlobal, $values.coreIndex)}}',
                    },
                  },
                }}
              />
            </SchemaField.Object>
          </SchemaField.Void>
        </SchemaField>
      </FormProvider>
    </>
  );
};

```
-  目前提供的FormilyLayout组件和FormilyContainer组件，都是基于Void Schema来实现的，从而不具有嵌套特性（虽然配置上有name，但是没有作用）
``` ts
// packages/formily-materials/src/shared/hoc/getSchemaComponent.tsx
export const createVoidSchemaComponent = (options: ICreateSchemaComponent) => {
  return createSchemaComponent({
    ...options,
    transform(schema) {
      // 拦截
      schema.type = 'void';

      return options?.transform?.(schema);
    },
  });
};

```

## 需求
先说一下，目前需求的背景：使用ali-lowcode-engine + formily来实现数据报表的查询联动，报表配置化中要实现的能力如下：
- 实现输入类组件到展示类组件的筛选，符合基本筛选诉求。
- 实现展示类组件到展示类组件的筛选，属于图表联动图表的高级功能。
- 实现输入类组件到输入类组件的筛选，属于筛选联动功能。
- 实现组件自身到自身的筛选，实现下钻功能。

目前的思路如下：
（1）、基于formliy封装FilterContainerRoot和FilterContainerItem组件，FilterContainerRoot对应为page层面，FilterContainerItem包裹每一层具有筛选能力的组件，从而将整个页面构建为一个大表单；
（2）、可以直接使用fomily-antd来满足不同场景的布局需要和筛选组件能力：https://antd.formilyjs.org/zh-CN/components
（3）、可以使用formily-react中内置的schema能力实现配置化表达：https://react.formilyjs.org/zh-CN/api/shared/schema
这个思路使用formily原生实现的demo，就是上述问题中描述的JSX，这个结构应该是可以通过ali-lowcode-engine配置出来的；

## 期望
- 目前是否有表单嵌套配置方向的规划，对于嵌套，目前的技术思路有没有大概的想法可以分享一下；
- 是否可以参与进来建设这块的能力；

**Comment by twinkle77** [comment]
@Immanding  老哥，加下我微信 18594013075

**Comment by Immanding** [comment]
首先欢迎共建。
你的问题不知道designable中的对象容器是否可以解决？可以的话你可以把对象容器接入进来。





------------------ 原始邮件 ------------------
发件人: BingBlog ***@***.***&gt;
发送时间: 2022年7月8日 11:23
收件人: seada-low-code/lowcode-ecology ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [seada-low-code/lowcode-ecology] form嵌套能力的实现 (Issue #5)





 
问题
  
如下所示，使用formily的Schema Markup方式或者完全schema的方式，都可以实现表单的嵌套； 
 /**  * @desc 构建全局和局部，并实现全局和局部查询参数的联动  * 1、日周月的类型会影响分析日期和对比日期  * 2、实时情况下，展示分时和累计切换  * 3、对比日期场景下，展示对比时间选择  *  */ import React from 'react'; import {   Input,   Select,   FormItem,   FormButtonGroup,   Submit,   FormLayout,   TreeSelect,   DatePicker,   Radio,   Checkbox,   Space, } from ***@***.***/antd'; import {   createForm,   onFormInit,   onFormMount,   onFormUnmount,   onFormReact,   onFormValuesChange,   onFormSubmit,   onFormSubmitStart,   onFormSubmitEnd,   onFormInitialValuesChange,   onFormInputChange, } from ***@***.***/core'; import { FormProvider, Field, createSchemaField } from ***@***.***/react'; import { FormilyTable } from './components/table'; import 'antd/dist/antd.css'; import './index.less'; const form = createForm({   effects() {     onFormInit(() =&gt; {       console.log('表单已初始化: ', form);     });     onFormMount(() =&gt; {       form.setValues({}, 'deepMerge');       console.log('表单已挂载: ', form.values);     });     onFormValuesChange((form) =&gt; {       console.log('表单值变化: ', form.values);     });   }, }); const SchemaField = createSchemaField({   components: {     FormItem,     Input,     DatePicker,     Radio,     Checkbox,     Space,     FormLayout,     FormilyTable,   }, }); export default () =&gt; {   return (     <&gt;       <FormProvider form={form}&gt;         <SchemaField&gt;           {/*************** topGlobal start ***************/}           <SchemaField.Void             x-component="FormLayout"             x-component-props={{               layout: 'inline',               labelAlign: 'right',               wrapperAlign: 'left',               className: 'material-search-form',             }}           &gt;             <SchemaField.Object name="topGlobal"&gt;               <SchemaField.String                 name="dateType"                 x-component="Radio.Group"                 x-component-props={{                   options: [                     { label: '日', value: 'day' },                     { label: '周', value: 'week' },                     { label: '月', value: 'month' },                   ],                   optionType: 'button',                 }}                 x-decorator="FormItem"                 default={2}               /&gt;               <SchemaField.String                 name="timeType"                 x-component="Radio.Group"                 x-component-props={{                   options: [                     { label: '离线', value: 2 },                     { label: '实时', value: 1 },                   ],                   optionType: 'button',                 }}                 x-decorator="FormItem"                 default={2}               /&gt;               <SchemaField.String                 name="analysticTimeType"                 default={1}                 x-component-props={{                   options: [                     { label: '分时', value: 1 },                     { label: '累计', value: 2 },                   ],                   optionType: 'button',                 }}                 x-component="Radio.Group"                 x-decorator="FormItem"                 x-reactions={{                   fulfill: {                     state: {                       display: '{{$values.topGlobal.timeType === 1 ? "visible" : "none"}}',                     },                   },                 }}               /&gt;             </SchemaField.Object&gt;           </SchemaField.Void&gt;           {/*************** coreIndex start ***************/}           {/*************** coreIndex filter start ***************/}           <SchemaField.Void             x-component="FormLayout"             x-component-props={{               layout: 'inline',               labelAlign: 'right',               wrapperAlign: 'left',               className: 'material-search-form',             }}           &gt;             <SchemaField.Object name="coreIndex"&gt;               <SchemaField.String                 name="date"                 x-component="DatePicker"                 x-decorator="FormItem"                 x-reactions={{                   fulfill: {                     schema: {                       'x-component-props.picker': '{{$values.topGlobal.dateType}}',                     },                   },                 }}               /&gt;               <SchemaField.String                 name="ratio"                 default={['_hb_ratio']}                 enum={[                   { label: '日环比', value: '_hb_ratio' },                   { label: '周同比', value: '_tb_ratio' },                   { label: '对比', value: '_compare_ratio' },                 ]}                 x-component="Checkbox.Group"                 x-decorator="FormItem"               /&gt;               <SchemaField.String                 name="compareDate"                 title="对比时间"                 x-component="DatePicker"                 x-decorator="FormItem"                 x-reactions={{                   fulfill: {                     state: {                       display:                         '{{$values.coreIndex.ratio.includes("_compare_ratio") ? "visible" : "none"}}',                     },                     schema: {                       'x-component-props.picker': '{{$values.topGlobal.dateType}}',                     },                   },                 }}               /&gt;             </SchemaField.Object&gt;           </SchemaField.Void&gt;           {/*************** coreIndex table start ***************/}           <SchemaField.Void             x-component="FormLayout"             x-component-props={{               layout: 'vertical',               wrapperWidth: '100%',             }}           &gt;             <SchemaField.Object name="coreIndexTable"&gt;               <SchemaField.String                 name="selectedNames"                 default={{                   selectedRowKeys: []                 }}                 x-component="FormilyTable"                 x-decorator="FormItem"                 x-component-props={{                   columns: [                     {                       title: '姓名',                       dataIndex: 'name',                       key: 'name',                     },                     {                       title: '年龄',                       dataIndex: 'age',                       key: 'age',                     },                     {                       title: '住址',                       dataIndex: 'address',                       key: 'address',                     },                   ]                 }}                 x-reactions={{                   fulfill: {                     schema: {                       'x-component-props.filterParams': '{{Object.assign({}, $values.topGlobal, $values.coreIndex)}}',                     },                   },                 }}               /&gt;             </SchemaField.Object&gt;           </SchemaField.Void&gt;           {/*************** coreIndex chart start ***************/}           <SchemaField.Void             x-component="FormLayout"             x-component-props={{               layout: 'vertical',               wrapperWidth: '100%',             }}           &gt;             <SchemaField.Object name="coreIndexTable2"&gt;               <SchemaField.String                 name="selectedChart"                 x-component="FormilyTable"                 x-decorator="FormItem"                 x-component-props={{                   columns: [                     {                       title: '姓名',                       dataIndex: 'name',                       key: 'name',                     },                     {                       title: '年龄',                       dataIndex: 'age',                       key: 'age',                     },                     {                       title: '住址',                       dataIndex: 'address',                       key: 'address',                     },                   ]                 }}                 x-reactions={{                   fulfill: {                     state: {                       display:                         '{{ $values.coreIndexTable.selectedNames.selectedRowKeys.length &gt; 0 ? "visible" : "none" }}',                     },                     schema: {                       'x-component-props.filterParams': '{{Object.assign({}, $values.topGlobal, $values.coreIndex)}}',                     },                   },                 }}               /&gt;             </SchemaField.Object&gt;           </SchemaField.Void&gt;         </SchemaField&gt;       </FormProvider&gt;     </&gt;   ); };
  
目前提供的FormilyLayout组件和FormilyContainer组件，都是基于Void Schema来实现的，从而不具有嵌套特性（虽然配置上有name，但是没有作用） 
 // packages/formily-materials/src/shared/hoc/getSchemaComponent.tsx export const createVoidSchemaComponent = (options: ICreateSchemaComponent) =&gt; {   return createSchemaComponent({     ...options,     transform(schema) {       // 拦截       schema.type = 'void';       return options?.transform?.(schema);     },   }); };
 
需求
 
先说一下，目前需求的背景：使用ali-lowcode-engine + formily来实现数据报表的查询联动，报表配置化中要实现的能力如下：
  
实现输入类组件到展示类组件的筛选，符合基本筛选诉求。 

实现展示类组件到展示类组件的筛选，属于图表联动图表的高级功能。 

实现输入类组件到输入类组件的筛选，属于筛选联动功能。 

实现组件自身到自身的筛选，实现下钻功能。 
 
目前的思路如下：
 （1）、基于formliy封装FilterContainerRoot和FilterContainerItem组件，FilterContainerRoot对应为page层面，FilterContainerItem包裹每一层具有筛选能力的组件，从而将整个页面构建为一个大表单；
 （2）、可以直接使用fomily-antd来满足不同场景的布局需要和筛选组件能力：https://antd.formilyjs.org/zh-CN/components
 （3）、可以使用formily-react中内置的schema能力实现配置化表达：https://react.formilyjs.org/zh-CN/api/shared/schema
 这个思路使用formily原生实现的demo，就是上述问题中描述的JSX，这个结构应该是可以通过ali-lowcode-engine配置出来的；
 
期望
  
目前是否有表单嵌套配置方向的规划，对于嵌套，目前的技术思路有没有大概的想法可以分享一下； 

是否可以参与进来建设这块的能力；

**Comment by BingBlog** [comment]
## 更新
1、尝试做了一下代码上的修改，发现：
```ts
// packages/formily-materials/src/shared/hoc/getSchemaComponent.tsx
export const createVoidSchemaComponent = (options: ICreateSchemaComponent) => {
  return createSchemaComponent({
    ...options,
    transform(schema) {
      // 拦截
      schema.type = 'object';

      return options?.transform?.(schema);
    },
  });
};
```
将`schema.type = 'void';`更改为`schema.type = 'object';`可以实现嵌套效果；
![image](https://user-images.githubusercontent.com/22095959/177914973-ab34d5ae-01b9-4e50-b093-e0d42ede85bf.png)

2、但是Select和Switch有效果，Radio和TextArea都不行，目前判断可能和`transform`处理有关系
```ts
export default createSchemaComponent({
  componentName: 'Radio.Group',
  component: Radio,
  transform(schema) {
    return schema;
  },
});
```
3、应该需要增加表达object类型的容器来实现嵌套

**Comment by twinkle77** [comment]
新增 ObjectField 组件 https://github.com/seada-low-code/lowcode-ecology/blob/main/packages/formily-materials/src/components/Object/index.tsx
