### ISSUE TITLE
是否支持 antd@5 ?

### ISSUE THREAD

**Issue by StringKe** [seada-low-code/lowcode-ecology#55]
https://antd5.formilyjs.org/zh-CN/components

formilyjs 这边已经支持 antd5 了

**Comment by haloworld007** [comment]
目前没有计划，因为[基础组件库物料](https://github.com/alibaba/lowcode-materials/tree/main/packages/antd-lowcode-materials)是基于 antd4 的，在把基础组件库物料升级到 antd5 之前估计都不会做这个事情
