### ISSUE TITLE
响应器无法使用

### ISSUE THREAD

**Issue by KellenHe** [seada-low-code/lowcode-ecology#56]
[https://github.com/alibaba/lowcode-engine/issues/1576](url)
这个问题还存在，能修复吗

**Comment by Immanding** [comment]
在内网的版本是ok的，周末有时间会看一下

**Comment by Immanding** [comment]
https://github.com/seada-low-code/lowcode-ecology/compare/main...fix_default

**Comment by Immanding** [comment]
@seada/antd-setters@1.0.0-rc.30
