### ISSUE TITLE
lowcode-ecology  的 Demo 文件夹内容 能否当成编辑器项目使用

### ISSUE THREAD

**Issue by yxiZo** [seada-low-code/lowcode-ecology#57]
## 场景描述

业务系统需要 formily 物料, 因此使用了本项目, 
业务系统本身需要嵌入 lowcode-engine , 根据[官方说法](https://github.com/alibaba/lowcode-engine/issues/2141#issuecomment-1577810828)是不支持 spa 接入方式,

所以我的方案是单开一个编辑器, 业务系统通过 iframe 或者 微前端引入编辑器项目

所以想咨询一下  ,  源码我看了一下, Demo 文件夹本地正常启动 , 但是打包后的产物可能有点问题, 如果需要的话我可以提交 pr, 期待回复

**Comment by Immanding** [comment]
不太了解你们的项目，这个项目只是lowcode-engine的一个物料而已，先在你们的项目中根据 lowcode-engine 的文档接入编辑器和渲染器，然后根据你们的需要接入物料就好。

**Comment by yxiZo** [comment]
了解, 感谢回复.
