### ISSUE TITLE
lowcode文件夹内容无变化

### ISSUE THREAD

**Issue by jingjingzhao** [seada-low-code/lowcode-ecology#6]
无论是新增`component`，还是删除整个`lowcode`文件夹，执行 `yarn lowcode:dev` ，lowcode文件夹都无反应。

要怎么操作或修改，才能使lowcode下生成新的组件？

**Comment by twinkle77** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/17792166/178957282-8d65a6c0-8367-4499-86cf-75cc7d912ce0.png">
解析后的文件到 npm 目录

还有就是，重新装下包 @jingjingzhao

**Comment by jingjingzhao** [comment]
> 


> <img alt="image" width="357" src="https://user-images.githubusercontent.com/17792166/178957282-8d65a6c0-8367-4499-86cf-75cc7d912ce0.png">
> 
> 解析后的文件到 npm 目录
> 还有就是，重新装下包 @jingjingzhao

那要手动生成 `lowcode` 文件吗？将 npm文件夹下的 copy 到 lowcode 下吗？
