### ISSUE TITLE
FormilySchemaSetter中使用effects报错

### ISSUE THREAD

**Issue by xyouZone** [seada-low-code/lowcode-ecology#60]
在使用formilySchemaSetter的物料的createFormItemSchema函数中添加effects，报错：Error: Consume method cannot be used in asynchronous function body
![image](https://github.com/seada-low-code/lowcode-ecology/assets/50430396/6237d218-3cac-4e05-b7f2-7bb4f33af481)

复现步骤：在formily-materials/lowcod/utils/formilyFieldShared-index文件中，给FormilySchemaSetter的props添加effects
![image](https://github.com/seada-low-code/lowcode-ecology/assets/50430396/0ad831e8-3296-4373-83dc-4b40c0a2bd16)
我想实现的功能是在设置器中实现配置的联动，比如在修改一项配置的同时自动修改另一设置项的下拉选项。我看formilySchemaSetter的props里面是有effects这个属性的，是我使用的问题还是bug?

**Comment by Immanding** [comment]
我没试过这么玩行不行，不过除了使用 effect 外你也可以自己封装一个组件实现联动的逻辑，然后把它加到 setter 里

**Comment by xyouZone** [comment]
> 我没试过这么玩行不行，不过除了使用 effect 外你也可以自己封装一个组件实现联动的逻辑，然后把它加到 setter 里

这个自己加到setter里是自己写一个新的设置器吗？还是说formilySchemaSetter里有设置的地方？

**Comment by Immanding** [comment]
自己写一个新的设置器一了百了，可以满足自己的所有需求，怎么写可以参考formily自定义组件接入。因为formilySchemaSetter实际上就是一个formily form
