### ISSUE TITLE
如何把自动生成的npm下的文件生成到lowcode

### ISSUE THREAD

**Issue by jingjingzhao** [seada-low-code/lowcode-ecology#7]
开发文档能否完善下？

遇到的问题：新增了components源码，重新执行`yarn lowcode:dev`，可以在npm文件夹下生成对应meta了。但是npm文件下的内容和 lowcode 文件夹下的内容是如何转化的？感觉是个黑盒啊。

另外一个疑问：官方物料脚手架执行`yarn lowcode:dev`会自动生成lowcode文件下的组件低代码，为何该项目是自动生成npm文件夹？与官方有何不同吗？

**Comment by twinkle77** [comment]
@jingjingzhao 生成位置不对，这个我看下

另外，开发 formily 组件的话，meta 大多都是从  designable 复制过来的 https://github.com/alibaba/designable/blob/main/formily/antd/src/schemas/Cascader.ts

**Comment by twinkle77** [comment]
@jingjingzhao  这个包现在已经开源了，但文档没跟上去，可以直接看源码了 😂 https://github.com/alibaba/lowcode-tools/blob/main/packages/build-plugin-lowcode/src/index.js#L583
